version: '3.8'
services:
  research-app:
    build:
      context:.
      dockerfile:.devcontainer/Dockerfile
    # Add capabilities and PID namespace for eBPF execution
    cap_add:
      - SYS_ADMIN
    pid: host
    volumes:
      -.:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount essential kernel filesystems for eBPF operation
      - /sys/kernel/btf:/sys/kernel/btf:ro
      - /sys/kernel/debug:/sys/kernel/debug:rw
    command: sleep infinity