    [package]
    name = "lock-common"
    version = "0.1.0"
    edition = "2021"
    publish = false

    [features]
    default = []
    user = ["aya"]

    [dependencies]
    aya = { version = "0.13.1", optional = true }

    [lib]
    path = "src/lib.rs"
