[package]
name = "lock-ebpf"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya-ebpf = "0.1"
aya-log-ebpf = "0.1"
lock-common = { path = "../lock-common" }
num_enum = { version = "0.7", default-features = false }

[[bin]]
name = "lock"
path = "src/main.rs"
