[build]
target = "bpfel-unknown-none"

[target.bpfel-unknown-none]
linker = "bpf-linker"
rustflags = [
    "-C", "panic=abort",
    "-C", "lto=yes",
    "-C", "codegen-units=1",
    "-C", "debuginfo=2",
    "-C", "link-arg=--btf"
] 