name: Build Paper

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'paper/**'
      - '.github/workflows/latex-build.yml'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'paper/**'

jobs:
  build-paper:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: paper/main.tex
        working_directory: paper/
        continue_on_error: true
    
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: paper-pdf
        path: paper/main.pdf
        retention-days: 30 