name: Lint

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: |
        uv pip install --system ruff black mypy jsonschema
    
    - name: Run Ruff
      run: ruff check .
    
    - name: Run Black
      run: black --check .
    
    - name: Run MyPy
      run: mypy . || true
    
    - name: Validate task schemas
      run: |
        for task in bench/tasks/*.json; do
          python -m jsonschema bench/schema/task.schema.json -i "$task"
        done 